# Generated by Django 5.2.3 on 2025-06-30 05:55

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='users/default_user.png', null=True, upload_to=users.models.Profile.generateImagePath),
        ),
    ]
