# Generated by Django 5.2.3 on 2025-07-11 05:39

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='static/images/blog1.png', null=True, upload_to=blogs.models.Blog.generateImagePath),
        ),
    ]
