# Generated by Django 5.0.3 on 2025-07-14 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.category'),
        ),
    ]
