# Generated by Django 5.0.3 on 2025-07-14 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_blog_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Category',
            new_name='category',
        ),
    ]
