# Generated by Django 5.2.3 on 2025-07-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_rename_category_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
    ]
