# Generated by Django 5.2.3 on 2025-07-29 05:47

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='blog/blog1.png', null=True, upload_to=blogs.models.Blog.generateImagePath),
        ),
    ]
